### ISSUE TITLE
paper-input two-way binding with shadow is not working on chrome

### ISSUE THREAD

**Issue by ebidel** [PolymerElements/paper-input#297] opened 2016-01-03 14:18 UTC
_From @robertsab on December 29, 2015 9:24_

paper-input two-way binding with shady is working on chrome(ubuntu 47.0.2526.106 (64-bit)) and it is not working with shadow on chrome

using Polymer 1.2.1.

_Copied from original issue: Polymer/polymer#3244_

**Comment by ebidel** [comment] 2016-01-03 14:18
_From @zoechi on December 29, 2015 11:8_

"it's not working" is pretty vague. Can you provide a Plunker that demonstrates the issue?

**Comment by ebidel** [comment] 2016-01-03 14:18
_From @robertsab on December 29, 2015 11:58_

http://jsbin.com/gojuseremi/edit?html,output , value is not updating.

**Comment by notwaldorf** [comment] 2016-01-05 23:01
What's happening is that `paper-input` doesn't have an `input` event, so `foo::input` doesn't mean anything. I've updated the jsbin using `::input` for a native input (where this event exists), and no event at all (i.e. just the value changing) for the `paper-input`: http://jsbin.com/xasesu/edit?html,output. You can also see that the event listener for `paper-input` for `input` isn't getting fired in the shadow DOM either.

The reason why this works in the shady DOM is probably because proper encapsulation is a wash, so the `input` event bubbles up from the nested `input` to the outside.

Closing this, since I think this is working as intended (given the available events of `paper-input`)

**Closed by notwaldorf** 2016-01-05 23:01 UTC

**Comment by jiettu** [comment] 2017-06-13 14:25
Does that mean paper-input was never meant to be two way bindable? I just updated my project to Polymer 2.0 and two way binding on paper input value stopped working.

**Comment by bennypowers** [comment] 2017-09-08 14:54
FWIW I also have this problem when I update my project to 2.0

I can enter text into the paper input, but the label doesn't float until I blur the input.

When I inspect the paper-input element, it's `value` is empty, although if I inspect the paper-input's internal `input` element, it has a `value`


![paper-input](https://user-images.githubusercontent.com/1466420/30217417-bfc7693c-94be-11e7-91aa-fcb871d9bbd3.gif)

**Comment by zoechi** [comment] 2017-09-08 15:01
@bennypowers I think it's better to create a new issue instead of commenting on a closed one.
This one is also quite old.

**Comment by bennypowers** [comment] 2017-09-08 15:17
👍 https://github.com/PolymerElements/paper-input/issues/567
