### ISSUE TITLE
paper-input underline no longer reflect focus

### ISSUE THREAD

**Issue by david-saslawsky** [PolymerElements/paper-input#108] opened 2015-06-30 19:48 UTC
Try to set the focus on input elements in https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html, the underline no longer animate to show the element with focus.

I think it may have something to do with the capturing event listener both in `paper-input-container` and in `IronControlState` (imported through `paper-input-behavior`). See:

``
this.addEventListener('focus', this._boundOnFocus, true);
``

**Comment by morethanreal** [comment] 2015-07-06 21:26
This is a duplicate of https://github.com/PolymerElements/paper-input/issues/99.

**Comment by notwaldorf** [comment] 2015-08-17 22:14
Closing as duplicate

**Closed by notwaldorf** 2015-08-17 22:14 UTC
Labels: duplicate
