### ISSUE TITLE
paper-input floating label does not came back when binded value is reset

### ISSUE THREAD

**Issue by monas** [PolymerElements/paper-input#431] opened 2016-09-01 11:14 UTC
### Description

Paper-input label position stays on after value is reset programatically. If I delete input value and unfocus input then label becomes a placeholder again. I would expect that same behaviour in case of binded value reset.
### Steps to reproduce

1. Put a `paper-input` element into the form.
2. Open the page in a web browser.
3. Click the `paper-input` element.
4. Change value
5. Reset form with reset button
6. Label will remain floated to top

### Browsers Affected

- [+] Chrome
- [+] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment] 2016-09-06 21:06
Closing, as I can't reproduce this: http://jsbin.com/quxolu/edit?html,output. Please re-open if you have a JSBin with repro steps.

Note that a `paper-input` does not work inside a normal, native `form` element -- you have to use an `iron-form` for that.

**Closed by notwaldorf** 2016-09-06 21:06 UTC
