### ISSUE TITLE
list property not bound when using shadow dom (instead of shady)

### ISSUE THREAD

**Issue by toddradigan** [PolymerElements/paper-input#399] opened 2016-06-23 20:58 UTC
### Description
When binding the list property of the paper-input (to use as an autocomplete with a datalist), this works correctly when using shady dom, but not when using shadow dom

### Expected outcome

datalist is bound correctly to the underlying iron-input, and autocomplete suggestions show when typing

### Actual outcome

inspecting the list property of the iron-input shows null, and no autocomplete suggestions show when typing

### Live Demo
the following JSBin shows it working correctly.  However, on line 8, change dom: 'shady' to dom: 'shadow', and it will no longer work correctly.

https://jsbin.com/holawifuye/edit?html,output

### Steps to reproduce

1. Put a `paper-input` element in the page.
2. Put a `datalist` in the page, with some option values
3. Set the list property of the paper-input to the id of the datalist
4. Set the polymer config to use shadow dom instead of shady
5. Open the page in chrome.
6. Begin typing in the input, one of the option values from the datalist

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

* others likely affected too, but the JSBin is short and doesn't worry about importing the polyfills

**Comment by notwaldorf** [comment] 2016-06-27 21:38
Oh interesting. I wonder whether this is because the input in the shadow DOM doesn't have access to the datalist, which is outside the shadow DOM.

As a workaround, you can use the `paper-input-container` directly: https://jsbin.com/xojule/edit?html,output

**Comment by notwaldorf** [comment] 2016-06-27 21:48
Ahhhh, I understand. So this is not a problem with `paper-input`, it's with the shadow DOM. As a side note, this happens with a plain input inside a shadow root as well: http://jsbin.com/sabafa/edit?html,output

The problem is that `input` needs to use an element's `id` that's in the same scope. Shadow DOM gives you encapsulation, which means the `input` and the `datalist` need to be in the same scope (either both in the same shadow root or not). Since in a  `paper-input` the `input` is in the shadow root but the `datalist` isn't, it won't work.

The `paper-input-container` example will work, though, since in that case the `input` and the `datalist` are in the same scope.

Closing, as this is working according to the shadow DOM rules.

**Closed by notwaldorf** 2016-06-27 21:48 UTC

**Comment by toddradigan** [comment] 2016-06-28 15:46
That makes perfect sense.  Thanks for the quick resolution!
