### ISSUE TITLE
Typing in a character puts cursor at end of input

### ISSUE THREAD

**Issue by wuxiaoying** [PolymerElements/paper-input#34] opened 2015-05-21 21:23 UTC
Type in a character anywhere at the start of an input. The cursor always moves to the end of the input.

**Comment by abourget** [comment] 2015-05-23 18:29
Same thing here ! just a little annoying :)

**Comment by abourget** [comment] 2015-05-23 18:31
Doesn't do it with a textarea, only with the line input.

**Comment by abourget** [comment] 2015-05-23 18:39
Actually, this is reproducible with only:

          <input is="iron-input" value="{{mama}}">

so this seems to be an `iron-input` issue. Think we can close this one.

**Comment by morethanreal** [comment] 2015-05-25 20:32
Fixed in PolymerElements/iron-input@8c1c8c409e7c6a31ffc245f589f75f984ada61b4

**Closed by morethanreal** 2015-05-25 20:32 UTC
