### ISSUE TITLE
iron-input validity/validationMessage

### ISSUE THREAD

**Issue by govis** [PolymerElements/paper-input#42] opened 2015-05-26 22:07 UTC
I see that there's been some work done in "allow manual validation - pull #26", but as of current bits paper-input doesn't seem to pickup changes to the iron-input's validity until it's validate() method is called and validationMessage is never looked at. Should we expect seamless support for the underlying html input validity attributes in paper-input/paper-textarea or do we need to wire it up ourselves?

thanks

**Comment by morethanreal** [comment] 2015-05-26 23:39
If `auto-validate` is not set on `<paper-input>`, it will not reflect the validity until you call `validate()` by design. `validationMessage` is not supported - use `error-message` instead. Does this answer your question?

**Comment by govis** [comment] 2015-05-27 00:12
I see, thanks for your answer. I guess what I am after is a way to put the <code>paper-input</code> into an invalid state while providing error message at run-time, I am using external validation framework, so properties such as <code>required</code> or <code>pattern</code> are not set. I simply tried setting <code>error-message</code> and <code>invalid</code> properties but for some reason nothing happened. Am I missing something - is setting error-message and invalid not enough to change the state to red underline with an error message? I'm also not sure why would someone need to call <code>validate()</code> if there're no rules to validate against. Thanks again.

**Comment by morethanreal** [comment] 2015-05-27 05:50
There was an issue with setting `invalid` that's fixed in 16df1b08566c6d9f7be37aac44cd6c1da19e3b7d.

**Comment by govis** [comment] 2015-05-27 15:38
Thanks for looking into this. I do get the red underline now, but the error message has disappeared - it's seems to be missing in the demos too. Also, I think we would need to make the change across all control containing the paper-input-container including paper-textarea and gold inputs. thanks.

**Comment by govis** [comment] 2015-05-30 01:00
Thanks for fixing it, your turnaround time is impressive. And congrats on finally shipping Polymer 1.0, I'm hoping that no elements (like core-list) will be left behind:). Gold input elements might still need the same fix, but please close it you see fit.

**Comment by notwaldorf** [comment] 2015-06-01 17:41
The fix was in `iron-input`, so it should automagically work on any element using it (including the gold elements). And don't worry, `iron-list` is on the radar :)

**Closed by notwaldorf** 2015-06-01 17:41 UTC
