### ISSUE TITLE
2.0-preview paper-input type="number" does not update it's value when two way bound property changes

### ISSUE THREAD

**Issue by tirithen** [PolymerElements/paper-input#488] opened 2017-03-08 13:33 UTC
### Description

`<paper-input value="{{aValue}}" type="number"></paper-input>
`
Does not update when the property changes. For paper-input without type="number" it works as expected.

### Expected outcome

When there is a two way binding to a property on the class, the input should change it's value as soon as the property changes value.

Also, if the value is set from parent element like `<input-test a-value="14"></input-test>` (see example code below) the value should shown in the paper-input as well.

### Actual outcome

The value is only (at least visually) updated on the paper-inputs that does not have type="number" set.

### Live Demo

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>

    <script src="/bower_components/webcomponentsjs/webcomponents-lite.js"></script>

    <script>
      window.Polymer = {
        dom: 'shadow',
        lazyRegister: true
      };
    </script>

    <style>
      body {
        margin: 0;
        font-family: 'Roboto', 'Noto', sans-serif;
        line-height: 1.5;
        min-height: 100vh;
        opacity: 1;
        transition: opacity .25s ease-in-out;
      }

      .unresolved {
        opacity: 0;
      }
    </style>
  </head>
  <body>
    <link rel="import" href="/bower_components/paper-input/paper-input.html">
    <dom-module id="input-test">
      <template>
        <paper-input value="{{aValue}}" type="number"></paper-input>
        <paper-input value="{{aValue}}" type="number"></paper-input>
        <paper-input value="{{aValue}}" type="number"></paper-input>
        <paper-input value="{{aValue}}"></paper-input>
        <paper-input value="{{aValue}}"></paper-input>
        <paper-input value="{{aValue}}"></paper-input>
      </template>
      <script>
        /* global Polymer */

        class InputTest extends Polymer.Element {
          static get is() {
            return 'input-test';
          }

          static get config() {
            return {
              properties: {
                aValue: {
                  type: Number,
                  value: 10
                }
              }
            };
          }
        }
        customElements.define(InputTest.is, InputTest);
      </script>
    </dom-module>
    <input-test a-value="14"></input-test>
  </body>
</html>
```

### Steps to reproduce

1. Paste above code into a HTML file
2. In the same directory run $ bower install polymer#2.0-preview paper-input#2.0-preview
3. Serve the files with a HTTP server
4. Load the page
5. Observe the initial state where the values should have been set to 14 (but are not)
6. Change the value in one of the top three input fields (that has type="number")
7. Observe the whether all the other fields change their values

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by Any1s** [comment] 2017-03-22 08:01
Reproduced this in
- [x] Chrome (stable) 57.0.2987.110
- [x] Opera 43
But it works in
- [x] Chrome (unstable) 59.0.3047.0 dev

**Comment by schrotie** [comment] 2017-04-01 20:35
Wanted to debug this, but works on Firefox Ubuntu and I cannot test on chromium due to [this bug](https://github.com/Polymer/polymer/issues/4444). Anyway, this simpler test-case reproduces it as well on Chrome on Android:
```
<!doctype html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, minimum-scale=1, initial-scale=1, user-scalable=yes">
		<title>test-paper-input</title>
		<script src="./bower_components/webcomponentsjs/webcomponents-loader.js"></script>
		<link rel="import" href="./bower_components/paper-input/paper-input.html">
	</head>
	<body>
		<paper-input
			type="number"
			label="foo"
			value="42"
		></paper-input>
	</body>
</html>
```

**Comment by notwaldorf** [comment] 2017-04-04 17:52
@tirithen Here is a jsbin with your code: http://jsbin.com/zifuhem/edit?html,output.
Make sure you put the Polymer related code in a `WebComponentsReady` listener, since polyfills are async, and if they need to be loaded, Polymer won't be loaded by the time the parser gets to that code.

You're right that the initial value is lost (looking into it), but updates definitely propagate -- make sure you type actual numbers, and not invalid `type=number` values (like `aaaa`), since it's a known issue that `<input type="number">` does not fire a change event if an invalid value is typed.

**Comment by notwaldorf** [comment] 2017-04-04 18:24
Ah, fixed. You need to use `get properties()` not `get config()`. Here's your original code, with the changes to make it work: http://jsbin.com/zifuhem/edit?html,output

Closing as resolved! 🎉

**Closed by notwaldorf** 2017-04-04 18:24 UTC
