### ISSUE TITLE
Does not add spellcheck attribute to iron-input

### ISSUE THREAD

**Issue by mikaelharsjo** [PolymerElements/paper-input#423] opened 2016-08-15 14:35 UTC
### Description
`paper-input` ignores the spellcheck attribute.

```html
<paper-input spellcheck="false"></paper-input>
```

### Expected outcome (simplified)

```html
<iron-input spellcheck="false">
```

### Actual outcome (simplified)

```html
<iron-input>
```

This is using latest (1.1.17) version.

**Comment by notwaldorf** [comment] 2016-08-16 00:23
Here's a jsbin where `spellcheck="false"` turns off the spellchecking correctly: http://jsbin.com/covihi/edit?html,output

Not all attributes are necessarily reflected in the internal `iron-input` -- for bound attributes, Polymer removes the attribute from the bound-to element.

Closing, as this seems to be working as intended, but please re-open if you have a jsbin with a reproducible problem.

**Closed by notwaldorf** 2016-08-16 00:23 UTC
