### ISSUE TITLE
Underline disappears sporadically as we zoom out.

### ISSUE THREAD

**Issue by StokeMasterJack** [PolymerElements/paper-input#448] opened 2016-10-13 17:12 UTC
Below are three screen shots at various zoom levels in Chrome:

**Large:**
![large](https://cloud.githubusercontent.com/assets/123349/19359084/62c6fa62-912d-11e6-9ed3-8090c366dc1f.png)

**Medium:**
![medium](https://cloud.githubusercontent.com/assets/123349/19359082/62c1adf0-912d-11e6-9af3-fb1da9ea6ba4.png)

**Small:**
![small](https://cloud.githubusercontent.com/assets/123349/19359083/62c3568c-912d-11e6-93ae-91a44f0058fc.png)

**Comment by freshp86** [comment] 2016-11-08 18:01
This is also affecting Chrome's MD Settings page, see [crbug.com/663304](https://bugs.chromium.org/p/chromium/issues/detail?id=663304).

**Comment by notwaldorf** [comment] 2016-11-08 19:34
Is this on Retina or non-retina? Sounds like a subpixel rounding error :(

**Comment by freshp86** [comment] 2016-11-08 19:38
I can reproduce both on a regular Dell 24 inch display, as well as on my Chromebook Pixel.

**Comment by notwaldorf** [comment] 2016-11-08 20:03
This definitely looks like subpixel problems. In this jsbin (http://output.jsbin.com/soqevu), the bottom two lines are just divs with heights of 1px and 2px (which is what a `paper-input` uses internally for the underline). On my retina Mac
- at 90% and 33% the 1px standalone underline disappears
- at 67% the 1px paper-input underline disappears
- at 25% both disappear

**Comment by notwaldorf** [comment] 2016-11-08 20:06
Moreover, this doesn't happen at all on Safari, and on FF only the 1px standalone underline disappears at the smallest possible zoom level, so this sounds to me like a Chrome bug. Closing :(

**Comment by freshp86** [comment] 2016-11-08 20:19
If you use bottom-border instead of a div, to represent the underline, I can no longer repro. Would that be a valid fix instead of just closing this issue?

**Comment by danbeam** [comment] 2016-11-10 23:10
as explained by @eaenet in https://trac.webkit.org/wiki/LayoutUnit, borders ensure they stay the right thickness as zoom changes (`LayoutUnit`s are the underlying units used for subpixel rendering, or at least they were at a time).

@notwaldorf I'm hitting very similar issues in Firefox 49.0.2 on https://jsfiddle.net/ea2hjbz7/1/: dropping or fattening of lines implemented with `<div style="height: ...">` (but not with `border`).

I can see a few options:

1. attempt to fix this for all users of `<paper-input{,-container}>` like this https://github.com/PolymerElements/paper-input/compare/master...border-bottom
2. Chrome forks paper-input-container.html to fix only our chrome:// pages :disappointed: 

1 seems like a _wayyyyy_ better idea to me.

**Comment by eaenet** [comment] 2016-11-10 23:45
As @danbeam mentioned above borders have special logic to ensure that a border that is at least one css pixel in thickness is never rounded down to less than one device pixel and thus is always painted regardless of zoom level.
This *only* applies to borders, elements with a solid background color and a fixed size are handled just like any other box and tends to be rounded down one the width/height when the effective size is below 1px.

**Comment by notwaldorf** [comment] 2016-11-15 19:46
fixed in https://github.com/PolymerElements/paper-input/pull/455

**Comment by danbeam** [comment] 2016-11-15 19:47
(and fix released in 1.1.21)

**Closed by notwaldorf** 2016-11-15 19:46 UTC
Labels: source: hooli
