### ISSUE TITLE
paper-textarea max-rows doesn't apply for wrapped text

### ISSUE THREAD

**Issue by lkovaleva** [PolymerElements/paper-input#359] opened 2016-03-14 20:28 UTC
Example on JsBin: http://jsbin.com/yepivolexi/1/edit?html,output

I expect both textareas to take up a maximum of 5 rows and generate a scrollbar, but only the one with line breaks does.

![image](https://cloud.githubusercontent.com/assets/14207087/13758827/a95f787e-e9e8-11e5-8986-70bfccb82e5e.png)

**Comment by notwaldorf** [comment] 2016-04-14 05:03
Closing as a duplicate of https://github.com/PolymerElements/iron-autogrow-textarea/issues/32 (this is a problem with the underlying `iron-autogrow-textarea`)

**Closed by notwaldorf** 2016-04-14 05:03 UTC
