### ISSUE TITLE
Custom validation

### ISSUE THREAD

**Issue by Sinjins** [PolymerElements/paper-input#350] opened 2016-03-01 18:21 UTC
I am running into an issue with custom validation for paper-input.  Upon trying to implement custom validation in the same way as I have done successfully using gold-email-input, the custom validator does not fire.  I am not specifying a 'type' attribute on the paper-input element, as I am aware that doing so may override any custom validation, as previously reported.  Here is the SO question with details and code excerpts:  http://stackoverflow.com/questions/35708993/polymer-paper-input-custom-validator-issue

ps:  One difference not noted in the SO question, in the way that I am consuming the element that implements paper-input (as compared to how I am consuming the element that implements gold-email-input), is that it is being implemented within a template using is="dom-repeat" attribute.  I don't see how that would/should make any difference, but thought I'd mention it just in case.

**Comment by notwaldorf** [comment] 2016-04-14 05:01
The problem is that the `validator` is not a function, it's the name of an element that implements `IronValidatorBehavior`, like here (and also in the `paper-input` demo): http://jsbin.com/nizege/edit?html,output

Closing, as I think this is a misuse of the `validator` attribute. Please re-open if I misunderstood (also, if that's the problem, would you mind updating the SO question with this answer? Thanks!)

**Closed by notwaldorf** 2016-04-14 05:01 UTC
