### ISSUE TITLE
Paper-input not working properly when inside a div with a background-image in a ios device

### ISSUE THREAD

**Issue by felipecesar00** [PolymerElements/paper-input#469] opened 2016-12-20 15:54 UTC
When paper-input is put inside a div with a background-image or with a iron-image and you're using it in ios, if you start typing it won't appear the content you just typer until you focus out the input.

In my application page there is a div to capture leads and this bug may affect his experience because he may end up not tiping his email and I lost a lead.

It happens on chrome and safari in my ios device (running on a iphone 6)

To reproduce:
>Create a div or a iron-image with a background-image and after put a paper-input appearing in the middle of the div with the background-image. Then, access the page through an ios device and start typing anything in the input
>If you keep the div and just remove the background-image the paper-input works properly

**Comment by notwaldorf** [comment] 2017-01-05 00:09
Can you please link to a jsbin with reproducible steps? Here's an example to get you started: https://jsbin.com/cagaye/edit?html,output

**Comment by notwaldorf** [comment] 2017-04-18 02:51
Closing since there hasn't been any response

**Closed by notwaldorf** 2017-04-18 02:51 UTC
Labels: pending-response
