### ISSUE TITLE
First character is doubled on Firefox mobile for Android (latest)

### ISSUE THREAD

**Issue by StephenTurley** [PolymerElements/paper-input#273] opened 2015-12-08 17:09 UTC
I noticed this on an app I'm building and confirmed in the Elements catalog.

Steps to reproduce, browse to that paper-input demo in the elements catalog using Firefox for Android.
https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input

Start typing a word. You will notice that the first character is always doubled.

**Comment by notwaldorf** [comment] 2015-12-08 23:18
Yeah, I can repro this :(

**Comment by notwaldorf** [comment] 2016-01-28 23:55
Unfortunately, I have no idea why this is happening, or how to fix it. I assume there's a weird problem with the syncing between `value` and `bindValue`, maybe? Or maybe it's the FF browser being crazy? 

If anybody has any ideas, a PR would be much appreciated 😰

**Comment by jab** [comment] 2016-01-30 15:15
Just tried this myself. The first time, I typed one character, then instead of staying to the right of what I typed, the cursor was moved to the left. I typed another character, and then the first character I typed was erroneously duplicated, the second character I typed was added to the right, and the cursor moved back to the right of everything. After that, further input worked as expected, including backspacing, UNLESS I used backspace enough to clear the entire input. After backspacing over everything, entering "A" and then "b" resulted in "AbA", then entering "c" resulted in "AbcAbA", then entering "d" resulted in "AbcdAbcAbA". You can see there's a pattern here. And another issue is that this time, the cursor disappeared after entering the initial "A", and never reappeared while continuing to enter text (finally tried tapping inside the input and it did reappear then). I tested the password input and it was broken in similar but different ways, but hopefully it's the same root cause, and the above helps diagnose and fix both issues.

**Comment by StephenTurley** [comment] 2016-04-13 15:18
Looks like the latest update to firefox fixes this.

**Comment by notwaldorf** [comment] 2016-04-13 19:06
@StephenTurley Whoa, awesome! Thanks for reporting back! 

Closing, since I just tested this on Firefox 4.4 (the latest version from the play store) and can confirm it's fixed! 🎉🎉🎉

**Closed by notwaldorf** 2016-04-13 19:06 UTC
Labels: p0 - critical

**Comment by kr05** [comment] 2017-08-12 02:28
This is happening with Chrome:( I have the following gold-phone-input

`<gold-phone-input auto-validate required maxlength="12" invalid="{{invalid}}" value="{{phone}}"></gold-phone-input>`

which is nested inside a paper-dialog.

Chrome: 59.0.3071.125
OS: Android 6.0.1
gold-phone-input: 1.1.0
paper-input: 1.1.24
paper-dialog: 2.0.0
