### ISSUE TITLE
shift+tab doesn't focus the previous input

### ISSUE THREAD

**Issue by jab** [PolymerElements/paper-input#283] opened 2015-12-15 02:02 UTC
Reproduction steps:

1. Go to https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input
1. Give the second paper-input (the password one) focus
1. Hit shift+tab

Expected behavior:
- Focus moves to the previous paper-input (the one with label "label")

Observed behavior:
- Focus remains on the currently-focused paper-input

**Comment by jab** [comment] 2015-12-15 02:03
This was reported in Polymer/paper-input#2 and supposedly fixed a while ago, but apparently that's a different codebase. Not sure if this is a regression or was just never implemented in this codebase.

**Comment by notwaldorf** [comment] 2015-12-15 03:36
What browser are you seeing this on? I've tried the demo on Chrome/Firefox/Safari/IE10 and it works on all of them. Here's a gif from chrome:

![inputs](https://cloud.githubusercontent.com/assets/1369170/11801369/f14a727e-a299-11e5-907e-e199e79dc008.gif)

**Comment by jab** [comment] 2015-12-15 03:46
Very strange. This was in Chrome, and I can consistently reproduce including in an incognito window:
https://youtu.be/ePynOwORQZg
Here's my Chrome version:
![screen shot 2015-12-14 at 22 41 12](https://cloud.githubusercontent.com/assets/64992/11801509/7ddd6ef2-a2b4-11e5-81dd-4f469c4c77d0.png)

Just tried in Safari and it did work. Any other info I can provide to debug?

**Comment by notwaldorf** [comment] 2015-12-15 19:05
I think in your youtube demo the overlay keyboard might be stealing the focus, and that's why tabbing is broken. I can't repro on a plain incognito window locally. How does this jsbin work differently: http://output.jsbin.com/bizoroj for you? (make sure you use the non-editable jsbin link, since the edit mode has all sorts of focus issues). 

Just want to double check this isn't the catalog misbehaving, for example.

**Comment by jab** [comment] 2015-12-15 21:39
I only added the overlay keyboard for the purposes of the screen recording. I promise it still happens on the catalog demo (and in my own app, which is where I first noticed it) without the overlay keyboard. Just tried your jsbin and it happens there too.

**Comment by notwaldorf** [comment] 2015-12-15 22:09
I think this might be an `iron-a11y-keys` bug. I opened it at https://github.com/PolymerElements/iron-a11y-keys-behavior/issues/28

(what's happening in `paper-input` is that the key binding for `shift+tab` is never hit, so we don't change the focus accordingly)

**Comment by jab** [comment] 2015-12-15 22:38
Thanks for chasing this down @notwaldorf! Subscribed over at that other issue.

**Comment by notwaldorf** [comment] 2016-01-05 23:49
Closing this, since it's not a `paper-input` bug

**Closed by notwaldorf** 2016-01-05 23:49 UTC

**Comment by jab** [comment] 2016-01-08 18:08
Looks like the fix for PolymerElements/iron-a11y-keys-behavior#28 was just merged to master :sparkles:

Is there an easy way to get a jsbin which repros this bug to point to latest master to see if that fixed this?

**Comment by userquin** [comment] 2016-04-02 15:13
This bug is still reproducible under linux (ubuntu 14) with firefox (version 45): on chromium works ok (firefox in windows 7/10 also works).

I'm using PSK version 1.2.3.

**Comment by notwaldorf** [comment] 2016-04-04 20:00
@userquin Can you repro the bug directly on the polymer elements demo? (i.e. https://elements.polymer-project.org/elements/paper-input?active=paper-input&view=demo:demo/index.html)

@valdrinkoshi If this is still reproducible (on Linux), do you think it's related to the change that also broke `esc` recently?

**Comment by valdrinkoshi** [comment] 2016-04-04 21:19
@notwaldorf not really, the `esc` bug was specific to chrome canary only ([see issue](https://github.com/PolymerElements/iron-a11y-keys-behavior/issues/38)), which is anyways fixed & released in `iron-a11y-keys-behavior v1.1.2`

**Comment by userquin** [comment] 2016-04-05 07:09
@notwaldorf 
On Centos7 (this evening I'll try at home with ubuntu) using Firefox  I can reproduce this bug, shift+tab not working on the first sample with 3 paper-input on the polymer elements demo.

There is a strange behavior when adding inside paper-input a  paper-icon-button with suffix and  attribute. Using shift+tab keys the paper-input never get focus, only the paper-icon-button. Using tab key, focus sequence order is correct: paper-input -> paper-icon-button -> next paper-input and so on:

Shadow DOM:
http://jsbin.com/yopigay/edit?html,output
Shady DOM:
http://jsbin.com/qipopo/edit?html,output

**Comment by userquin** [comment] 2016-04-16 10:09
@notwaldorf 
Also confirmed on Ubuntu, polymer elements demo not working on Firefox.

**Comment by userquin** [comment] 2016-05-11 18:58
@notwaldorf 
some progress in this ???

**Comment by notwaldorf** [comment] 2016-05-11 19:01
Unfortunately, I can't make a lot of progress on this since i only have Mac and Windows machines, and on those, in Firefox, the demo looks fine :(

Any pointers would be appreciated.

**Comment by userquin** [comment] 2016-05-12 08:08
How about focus behavior when adding buttons with suffix inside paper-input (shady and shadow, any browser, any OS)???

I'll try to fix it on FF.

About your environment: install Oracle Virtual Box (free), find an ISO for Centos or Ubuntu and that's all.

**Comment by umbertoand** [comment] 2019-02-27 11:07
Hi @notwaldorf, this bug seems to have reappeared on Firefox as per the original description.
- On firefox production, tabbing and shift-tabbing seem to be broken.
- On firefox nightly, only shift-tabbing is broken.

**Comment by notwaldorf** [comment] 2019-02-27 17:46
Unfortunately, I no longer work on this project and don’t have the bandwidth to take a look. Maybe @bicknellr can triage this? 🙏

**Comment by notwaldorf** [comment] 2019-02-27 17:46
Though since the issue is closed, I recommend just opening a new one

**Comment by umbertoand** [comment] 2019-02-27 17:56
Thanks for the prompt reply! Have created a new issue at #690
