### ISSUE TITLE
Demo bug

### ISSUE THREAD

**Issue by khoanguyenlio** [PolymerElements/paper-input#362] opened 2016-03-17 08:36 UTC
In demo on paper-input, I found this: 
![bugdemo](https://cloud.githubusercontent.com/assets/9152575/13840553/aee114dc-ec55-11e5-86ec-91e545980825.jpg)
It's problem of  type="number" or paper-input?

**Comment by notwaldorf** [comment] 2016-03-21 17:50
There seems to be a problem with `input type="number"` and invalid values.

**Comment by notwaldorf** [comment] 2016-04-14 05:16
Closing as duplicate of https://github.com/PolymerElements/paper-input/issues/362 (since that one has a better title)

**Closed by notwaldorf** 2016-04-14 05:16 UTC
Labels: p0 - critical
