### ISSUE TITLE
Can not change style of paper-textarea to my needs.

### ISSUE THREAD

**Issue by krozycki** [PolymerElements/paper-input#327] opened 2016-02-04 11:44 UTC
Hi. I have a paper-textarea defined like this in my polymer element:

`          <paper-textarea
              id="description"
              name="description"
              label="Description"
              rows="7"></paper-textarea>`

and I want to style it so that the paper-input-container in it has `display: block;`. However, if I do:

`#description {
  --paper-input-container {
    display: block;
  }
}`

it affects also the label and it looses its default formatting(like color, font size, etc.). I don't know why that happens.

I managed to set the block display on paper-input-container without loosing label default styling by doing:

`#description ::content .input-content.paper-input-container {
  display: block;
}`

but is seems to touch the internal elements of paper-textarea in my code and because of that I thought maybe there is a better way to do this? Or is it impossible for now to do it nicer and it needs some work to be done?

**Comment by notwaldorf** [comment] 2016-02-04 20:20
I don't think I understand what you're trying to add `display:block` to? I don't see a visual difference between the two. Can you please provide some screenshots of what is happening and what you expect to happen?

**Comment by krozycki** [comment] 2016-02-05 10:20
![screengithub](https://cloud.githubusercontent.com/assets/4281416/12843510/ca1cf9ca-cbf1-11e5-8575-dd6aa83de5cd.png)

Without `display: block` the text gets out of the box.

With `#description { --paper-input-container { display: block; } }` the 'Description' label looses its styling.

The css rule `#description ::content .input-content.paper-input-container { display: block; }` works, but doesn't seem to be a nice solution as mentioned above.

**Comment by krozycki** [comment] 2016-02-22 14:43
Could you please remove 'pending-response' label?

**Comment by notwaldorf** [comment] 2016-02-22 20:11
The `pending-response` means I'm still waiting on an answer. I can't reproduce the "text going outside the box" bug, and I am not sure about what you're trying to fix.

Can you please provide a jsbin or something that I can actually run and see what you're doing? Do you want the `paper-textarea` to be a block? It already is by default. The `paper-input-container` is also already a block by default, so I don't understand why you'd want to change that (or why that would fix anything)

Here's an example to get you started: http://jsbin.com/pidafa/edit?html,output

**Comment by notwaldorf** [comment] 2016-07-07 14:57
Closing, as there hasn't been an answer in a long time

**Closed by notwaldorf** 2016-07-07 14:57 UTC
Labels: p1 - backlog, pending-response
