### ISSUE TITLE
Paper-textarea makes a form throw error if empty and never focused

### ISSUE THREAD

**Issue by AlexNasonov** [PolymerElements/paper-input#384] opened 2016-05-02 18:02 UTC
### Description
If there is a paper-textarea in a form, which was not eve once focused by user (f.e. not requred field) - it causes an error on form submit.

### Expected outcome

form.submit()

### Actual outcome

iron-request.html:424 Uncaught TypeError: Cannot read property 'toString' of undefined
Polymer._wwwFormUrlEncodePiece	@	iron-request.html:424
(anonymous function)	@	iron-request.html:412
Polymer._wwwFormUrlEncode	@	iron-request.html:407
Polymer._encodeBodyObject	@	iron-request.html:393
Polymer.send	@	iron-request.html:298
Polymer.generateRequest	@	iron-ajax.html:445
Polymer.submit	@	iron-form.html:251

### Steps to reproduce
1) create a form with textarea element
2) don't use it
3) submit the form

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment] 2016-05-31 18:10
Closing, as I can't reproduce this: http://jsbin.com/gesecah/edit?html,console. Can you please provide a jsbin with reproducible steps, and we can reopen this issue then.

**Closed by notwaldorf** 2016-05-31 18:10 UTC

**Comment by PFischbeck** [comment] 2016-06-10 11:34
I had the same error and managed to reproduce this: 
http://jsbin.com/tajexemuqa/edit?html,console,output
It seems to also occur in Firefox.

**Comment by Pablo-Aldana** [comment] 2017-03-05 08:30
Still happens even focusing the text area
It seems to be reproducible in Safari 10
