### ISSUE TITLE
on-value-changed fires twice on keypress.

### ISSUE THREAD

**Issue by andrepl** [PolymerElements/paper-input#66] opened 2015-06-06 01:11 UTC
just a simple paper-input with on-value-changed='myCallback', fires the value-change event twice for each keypress,  both events appear to be identical.

I've been having a hard time getting all the relevant imports in order to reproduce this in a jsbin, I've done so before where only polymer.html was required  but I can't find a host that has all of the required dependencies with the correct directory layout to get this working. (rawgit.com breaks the relative imports)

**Comment by morethanreal** [comment] 2015-06-08 23:38
This appears to be a Polymer issue: https://github.com/Polymer/polymer/issues/1791

**Comment by notwaldorf** [comment] 2015-10-23 20:09
I can't repro this anymore, and this is a very old issue. Please re-open if this still occurs!

**Comment by Saulis** [comment] 2016-03-02 13:21
Please reopen, here's a JSBin that reproduces the issue still on latest paper-input.

http://jsbin.com/niditu/edit?html,console,output

Also, `value-changed` is fired twice if `value` is set manually.

**Comment by Saulis** [comment] 2016-03-07 19:24
This might be related with fact that both IronFormElementBehavior and PaperInputBehavior declare the value property and set it to have notify:true.

**Comment by notwaldorf** [comment] 2016-03-07 19:25
@Saulis Yup, pretty sure that's exactly the problem.

**Comment by gaurav21r** [comment] 2016-07-26 21:20
@notwaldorf  Any updates on this issue? Can the priority be bumped up? Its affecting a lot of elements. Especially the `value` property. Too many events are firing which leads to performance losses!

**Comment by mercmobily** [comment] 2016-08-10 00:58
Another JSBin that shows the problem: https://jsbin.com/vojexe/edit?html,console,output
I remember reading the code for vaadin-combo-box, and noticing a line:

https://github.com/vaadin/vaadin-combo-box/blob/29ec860e8dafc22848bf1d328f5f7ecac14c9a9e/vaadin-combo-box-behavior.html#L44

I think they are having the same problem, and that's how they "solved" it (although it's really hardly a solution!)

I hope this helps...

**Comment by gaurav21r** [comment] 2016-08-10 17:29
@morethanreal @notwaldorf Can we at least bump this higher than `p1-backlog`?

**Comment by notwaldorf** [comment] 2016-08-10 17:40
My understand is that this is a Polymer issue; even if we bump the priority of _this_ issue, I can't really think of a way to fix it for this element without causing a breaking change to either behaviour :(

**Comment by mercmobily** [comment] 2016-08-10 18:13
Maybe we should report this to the main Polymer repository... shall I do
that?

**Comment by notwaldorf** [comment] 2016-08-10 18:41
@mercmobily If you check the [first comment](https://github.com/PolymerElements/paper-input/issues/66#issuecomment-110172202), it's already been reported :)

**Comment by mercmobily** [comment] 2016-08-11 00:19
I am gonna stop apologising with you Monica, it's getting repetitive... You
can just assume there is a "sorry" at the beginning of each one of my posts!

**Comment by kaste** [comment] 2016-08-11 14:59
Polymer/polymer#3856 now tries to solve this

**Comment by dman777** [comment] 2017-05-12 04:59
I hit this bug today. Can we re-open this since #3856 was never merged?

**Comment by TimvdLippe** [comment] 2017-08-17 02:08
This issue has been fixed in Polymer 2: http://jsbin.com/covezabevi/edit?html,console,output

**Closed by TimvdLippe** 2017-08-17 02:08 UTC
Labels: bug, p1 - backlog
