### ISSUE TITLE
lable disapears

### ISSUE THREAD

**Issue by TimWillis** [PolymerElements/paper-input#102] opened 2015-06-25 14:23 UTC
When I set bind-value={{address_1}} back to "" the label disappear until something is reentered in the input when I use chrome's form autocomplete.

                    <paper-input-container >
                        <label>Address Line 1</label>
                        <input  id="address_1" is="iron-input" type="text" name="address" required bind-value="{{address_1}}"
                                allowed-pattern="/^[a-z0-9]{2,30}$/"
                                autocomplete="address-line1">
                        <paper-input-error>Valid address required</paper-input-error>
                    </paper-input-container>

**Comment by morethanreal** [comment] 2015-07-07 22:55
@TimWillis Can you give a step-by-step process on how to reproduce this bug, preferably with example code? I cannot reproduce it by setting the `iron-input`'s `bindValue` to `''`, and I'm not sure how form autocompletion interacts with the test case.

**Comment by TimWillis** [comment] 2015-07-09 12:58
when I go to input an address I choose to use chrome's auto complete and select my address, then I submit and reset the form to "" , along with setting this.address_1 = "". When I do this ,it loses the place holder text and label. Here is a short video of the process.
https://drive.google.com/a/timtwillis.com/file/d/0B84VgdHjb1mnN3llU2F1NTQ2eDQ/view?usp=sharing

**Comment by notwaldorf** [comment] 2015-10-23 20:07
Closing, since this is very old and without repro steps. Please re-open if this is still an issue.

**Closed by notwaldorf** 2015-10-23 20:07 UTC
Labels: bug, pending-response
