### ISSUE TITLE
required auto-validate validates on element load

### ISSUE THREAD

**Issue by Junikorn** [PolymerElements/paper-input#204] opened 2015-10-14 14:24 UTC
```
<paper-input id="name" label="Name" value="{{name}}" required auto-validate></paper-input>
```

The field validation is triggered even if field hasn't been focused yet. (Occurs only on unvulcanized component).

**Comment by epworthhh** [comment] 2015-10-16 07:16
Any solution?

**Comment by Junikorn** [comment] 2015-10-16 15:50
It's non production so I considered it low priority. No solution yet. Maybe if I will have time I will take a look

**Comment by notwaldorf** [comment] 2015-10-16 16:04
I thiiiiink this is working as intended. `paper-input` will validate the element when it's attached if it has a non empty value: https://github.com/PolymerElements/paper-input/blob/master/paper-input-container.html#L436

I think the motivation is that if you start off with an invalid value in an input, you should inform the user it's invalid. However, if your input is empty, there's no reason informing the user that it's invalid, since they didn't really get to write anything yet, and the empty value doesn't mean anything at that point.

**Comment by Junikorn** [comment] 2015-10-16 16:29
In my case it validates element with empty value

**Comment by epworthhh** [comment] 2015-10-16 20:27
+1

**Comment by epworthhh** [comment] 2015-10-19 08:08
if I use just <paper-input> enter submit doesnt work but the validation is ok. If i use <paper-input-container>, enter submit works but validate the input on load.

**Comment by notwaldorf** [comment] 2016-01-28 23:29
Closing this, as I can't reproduce it. Here's a jsbin where i'm binding the value to both something that exists, and an empty value: http://jsbin.com/jokira/edit?html,output
In neither case does the validation get triggered.

Please re-open if you have a jsbin with reproducible steps.

**Closed by notwaldorf** 2016-01-28 23:29 UTC
