### ISSUE TITLE
Styling for errorMessage and charCounter

### ISSUE THREAD

**Issue by stramel** [PolymerElements/paper-input#583] opened 2017-10-27 19:38 UTC
### Description

`errorMessage` and `charCounter` aren't accounted for in styling so they are often clipped due to other elements sitting underneath it.

### Expected outcome

When an `errorMessage` or `charCounter` are present they should be fully displayed when another element is directly underneath it.

### Actual outcome

When an `errorMessage` or `charCounter` are present they are clipped when another element is directly underneath it.

### Live Demo

![image](https://user-images.githubusercontent.com/855184/32121961-61208b20-bb24-11e7-84c8-7c6c3cc71b82.png)

![image](https://user-images.githubusercontent.com/855184/32121998-7d29e51e-bb24-11e7-92ba-1a33114aadc7.png)

### Browsers Affected

I believe all of these are affected but I have only tried Chrome.

- [x] Chrome
- [x] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by xelra** [comment] 2017-12-02 21:12
I just ran into this problem myself. The funny thing is that it was working in my app and then suddenly I noticed the clipping just now.

Then I saw that even the demo is affected.
![image](https://user-images.githubusercontent.com/908568/33519752-b92cfb46-d7ad-11e7-95cf-98cb8f0386e0.png)

I can confirm that this also affects Firefox and Opera in addition to Chrome.

Does anyone have an intermediate fix? I've been playing with the CSS for some time now, but I just can't find the right values to change.

**Comment by xelra** [comment] 2017-12-05 21:41
I have identified the problem. `<paper-input-container>` is styled with `overflow: hidden`, which breaks the inheritance chain of visible overflow. Changing it to `overflow: inherit` or completely removing it from `:host {}` should fix the issue.

**Comment by notwaldorf** [comment] 2017-12-06 08:05
This bug was introduced in 2.0.4 (it was trying to fix something else,
sigh), and there’s a PR out to fix it! Will merge and do a release
tomorrow, hopeful. Sorry about that!

**Comment by notwaldorf** [comment] 2017-12-06 19:46
Closing as a dupe of #597, which has a better pinpoint to the actual error

**Closed by notwaldorf** 2017-12-06 19:46 UTC
