### ISSUE TITLE
Label highlight in Microsoft Edge

### ISSUE THREAD

**Issue by samiheikki** [PolymerElements/paper-input#329] opened 2016-02-08 11:25 UTC
Paper-input's label highlight (with prefix icon) shows double highlight in some cases.
When input is blurred a grey thick underline stays at the bottom of input.

Demo:
![paper-input-edge](https://cloud.githubusercontent.com/assets/8615573/12884425/d163c278-ce66-11e5-983a-d2c5ed108bf0.gif)

**Comment by notwaldorf** [comment] 2016-02-08 21:20
Yup, looks like a bug. It's probably one of the styles in `paper-input-container` that's a bit wonky. If you find it and want to send a PR to fix it, it would be very appreciated! 😻

**Comment by samiheikki** [comment] 2016-02-09 08:12
https://jsbin.com/caremabuye/5/edit?html,output Here is a simple jsbin for repeating the bug.

**Comment by notwaldorf** [comment] 2016-02-17 09:05
Blerg. Did a bunch of investigating (https://jsbin.com/roqudo/edit?html) and it seems that this only happens when the input is inside a form, and it happens for any `paper-input`. I'm noticing the weird bonus underline when just hovering over the input, but they aren't reproducible if the input is outside the form.

I tried to reset any relevant styles in different `:hover` selectors, and it doesn't make a difference. Oh, Edge.

**Comment by notwaldorf** [comment] 2016-02-17 18:35
Great. I just tried that demo on an actual Edge browser and not a VM (20.10240.16384.0) and I don't see any artifacts at all.

**Comment by notwaldorf** [comment] 2016-02-17 19:21
More updates! This seems to only happen on non-retina displays (and it looks fine on retina displays). There doesn't seem to be any changes in any of the applied/computed styles, so I'm suspicious this is a painting bug (and in particular, since the border seems to be 1px off, maybe there's some weird subpixel rounding going on?)

**Comment by Saulis** [comment] 2016-02-18 10:16
It seems to definitely be a rendering issue.

Tried paper-input demos on Elements Catalog with a Surface Pro 3 tablet having 2160x1440 resolution (recommended) and Edge 20.10240.16384, and also on a Win10 laptop having 1920x1080 resolution.

Turned out that the Surface tablet uses 150% Zoom level by default, and turning that down to 100% fixes the issue in most cases. Prefixed and suffixed inputs still have the problem. Turning the Zoom level down to 75% seems to fix those also :smile: 

The behaviour doesn't actually seem to be affected by resolutions (tried randomly a few), but mainly the Zoom level. The pattern seems to be consistent also on my VM (both Retina and non-Retina displays), but can't be 100% because the VM resolution is scaled.

I see this behaviour also on the JSBin by @samiheikki. In your JSBin the issue is more clear on the paper-inputs inside form, but if you look *really* closely, you can also see the underline of the paper-input outside a form change it's colour to a bit darker shade when hovered on.

We were able to alter the behaviour a bit by trying out setting `line-height: 0` to `paper-input #input` but couldn't find a setting that would work on all cases.

But anyways, to me it seems like Edge is adding some weird styles on input fields when hovered on.

**Comment by notwaldorf** [comment] 2016-02-19 18:41
Argh, then I'm tempted to close this, since I don't think there's anything we can do to fix this. It would be neat to file this as an Edge bug, though

**Comment by Saulis** [comment] 2016-02-22 08:12
Yeah I think its OK to close this, I've flagged the ticket at our end already to be a MS Edge bug.

Tried searching any information about this on the Edge "feedback" site, but had to give up because it really seems that Microsoft has intentionally engineered the site to be utterly unusable. Maybe to limit the incoming bug reports. :see_no_evil:

**Comment by notwaldorf** [comment] 2016-02-22 20:16
Closing! Blerg about the feedback site; I'll try to see if I can manage to file a bug

**Closed by notwaldorf** 2016-02-22 20:16 UTC
Labels: p0 - critical, pending-response
