### ISSUE TITLE
Floating label not animating on focus

### ISSUE THREAD

**Issue by jdepypere** [PolymerElements/paper-input#240] opened 2015-11-08 13:39 UTC
This is something that I've never noticed to misbehave until reading [this SO question](http://stackoverflow.com/questions/33583986/polymer-1-0-paper-input-label-not-floating) and looking at the [demo of `1.0.18`](https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input).

#### Expected outcome
1. When focusing on an empty `paper-input`, the label would animate from non-floating to floating ([the 0.5 demo page with sample](https://www.polymer-project.org/0.5/components/paper-elements/demo.html#paper-input), [Material Design Lite demo](http://codepen.io/anon/pen/vNVpmY)).
2. When losing focus of an empty input, the label should animate back to the none-floating position.

#### Actual outcome
1. On focus of an empty input field the label remains unfloated until the value is not empty. Only then does it float.
2. Once the value of the input is empty, the label goes to it's unfloated position. On top of that, it doesn't animate.

#### Steps to reproduce
[Check the regular demo page of `paper-input` version `1.0.18´](https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html&active=paper-input)

I'm running the stable Chrome channel, `46.0.2490.80 m`. For security I also checked in Firefox `40.0.3`, same result.

**Comment by notwaldorf** [comment] 2015-11-09 18:49
Many behaviours have changed between 1.0 and 0.5 -- in this case, the label will only float if it has content in it. This will make less of a busy/nauseating effect if, for example, you're tabbing through a form of empty fields -- they don't need to all float and then unfloat.

I'll close this as working as intended, since this was a deliberate change.

**Closed by notwaldorf** 2015-11-09 18:49 UTC

**Comment by jdepypere** [comment] 2015-11-10 09:07
That's too bad, it felt more pleasing before to me. I guess the [spec](http://www.google.be/design/spec/components/text-fields.html#text-fields-floating-labels) is also pretty open about this:

> When the user engages with the text input field, the floating inline labels move to float above the field.

I personally don't see the use case of tabbing through empty fields happening much other than to developers, but I guess enough to justify the change. Just wanted to check if it was intended, thanks for the reply!

**Comment by adolgoff** [comment] 2017-07-03 23:18
https://material.io/guidelines/components/text-fields.html#text-fields-states

There are the guidelines, which the components inherit, and there's some personal thoughts about how interfaces should behave in certain cases. And it's possibly could be some flag, but default behavior couldn't break the guidelines. It's simply UX guys expectations. 

The problem is also that user input and unfocused placeholder positions are different. So it break the carriage positioning too in case developers fix padding to valid ( = guidelines based).
