### ISSUE TITLE
Calling paperInput.focus() does not work

### ISSUE THREAD

**Issue by vinerz** [PolymerElements/paper-input#389] opened 2016-05-13 16:04 UTC
### Description
Calling paperInput.focus does not work

### Expected outcome
When calling `paperInput.focus()`, the paper-input element should be focused.

### Actual outcome
Nothing happens. Tried with some variations:
1. paperInput.focus();
2. paperInput.inputElement.focus();
3. paperInput.$.input.focus();

Interestingly, the autofocus property however, **does work**

### Live Demo
Example: https://elements.polymer-project.org/bower_components/paper-input/demo/index.html

### Steps to reproduce
1. Put a `paper-input` element in the page.
2. Open the page in a web browser.
3. Inspect the `paper-input`
3. Call a `$0.focus();` on the console.

### Browsers Affected

- [*] Chrome

* Could not test with another browser.

**Comment by notwaldorf** [comment] 2016-05-13 17:27
I think the problem is that the dev tools steal focus from you (and, in particular, the demo on the website is in an iframe).

Here's a jsbin where clicking the button focuses the third input, and that works fine: http://output.jsbin.com/zivunaz

Closing, as this isn't reproducible

**Closed by notwaldorf** 2016-05-13 17:27 UTC

**Comment by vinerz** [comment] 2016-05-13 20:29
Hello @notwaldorf! Thanks for the answer!

Maybe I am having a timing issue here.

I have this deeply nested chain of custom elements, and one of them has a login form. I am trying to accomplish the forced focus using this code:

```js
        attached: function() {
          this.async(function() {
            if (this.$.email.value !== '') {
              this.$.password.focus();
            } else {
              this.$.email.focus();
            }
          });
        }
```

I even tried to encapsulate that at async and at the attached event, to delay the most time as possible.
What am I doing wrong?

**Comment by notwaldorf** [comment] 2016-05-23 18:04
Could you make a small JSBin with repro steps similar to yours (or a smaller example) please? It's hard to tell what's going on without looking at the code... 

Check this element's CONTRIBUTING.md for an example JSBin, if you need to.
