### ISSUE TITLE
paper-input-container throwing uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by tupaje1** [PolymerElements/paper-input#521] opened 2017-04-19 19:36 UTC
### Description
The paper-input demo is not working. The `paper-input-container` element, line:513, is throwing uncaught TypeError: Cannot read property 'addEventListener' of null. The 'this._inputElement' is null.

### Expected outcome
The `paper-input` element should be clickable and allow user to enter a value.

### Actual outcome
The `paper-input` element is not clickable and does not allow user to enter a value

### Steps to reproduce
1. install `polymer-2-starter-kit` and `bower install PolymerElements/paper-input#2.0-preview PolymerElements/iron-demo-helpers#2.0-preview PolymerElements/iron-validator-behavior#2.0-preview`
2. run `polymer serve` 
3. Open the page in a web browser to "localhost:8080/components/paper-input/demo/".
3. Click the `paper-input` element.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

![screenshot](https://cloud.githubusercontent.com/assets/26467342/25199079/32e89fa0-250f-11e7-8727-bc65191c7a92.PNG)

**Comment by notwaldorf** [comment] 2017-04-19 21:21
I can't reproduce this. This is the demo, and it looks ok: http://polygit.org/polymer+v2.0.0-rc.4/webcomponentsjs+webcomponents+v1.0.0-rc.8/shadycss+webcomponents+1.0.0-rc.5/paper*+polymerelements+:2.0-preview/iron*+polymerelements+:2.0-preview/app*+polymerelements+:2.0-preview/neon*+polymerelements+:2.0-preview/components/paper-input/demo/index.html

Can you provide any more details, or maybe a jsbin with an example?

**Comment by hitokiri8x** [comment] 2017-04-20 10:25
Hello, 
I have the same problem, with only Chrome...
The sample of @notwaldorf   works fine, however with the latests version something is broken ( it broke after a bower update, while at the beginning worked fine ).
 
I'm on     "polymer": "Polymer/polymer#^2.0.0-rc.7",  and "webcomponentsjs": "^v1.0.0-rc.9"

**Comment by swypse** [comment] 2017-04-20 11:35
`bower_update` with:
```javascript
{
"dependencies": {
// ...
    "paper-input": "PolymerElements/paper-input#2.0-preview",
    "polymer": "Polymer/polymer#^2.0.0-rc.7",
    "webcomponentsjs": "webcomponents/webcomponentsjs#^1.0.0-rc.9",
},
"resolutions": {
// ...
    "polymer": "^2.0.0-rc.7",
    "webcomponentsjs": "1.0.0-rc.9"
}
}
```

helps me.

**Comment by mahdiridho** [comment] 2017-04-20 11:45
Same issue here after upgrade my projects to polymer2.0

If using paper-input version before 2.0, It cannot show the text input
After I update :

bower install --save PolymerElements/paper-input#2.0-preview

I got new errors, like [tupaje1](https://github.com/tupaje1) explained :
- Uncaught error of event listener on paper-input-container
- Uncaught error when click focus the text input

For temporary now, I change my paper-input to iron-input#2.0

**Comment by mahdiridho** [comment] 2017-04-21 04:15
notwaldorf..

I was installing with polymer init and choose 2.0 starter kit. Then I added some elements (included paper-input) follows this link: 

[Install Polymer 2.0](https://www.polymer-project.org/2.0/docs/about_20)

*) Note that some of the 2.0-preview branches are subject to change due to bug fixes.

Below was my bower.json with paper-input :

```
{
  "name": "polymer-starter-kit",
  "authors": [
    "The Polymer Authors"
  ],
  "license": "https://polymer.github.io/LICENSE.txt",
  "dependencies": {
    "polymer": "Polymer/polymer#^2.0.0-rc.3",
    "app-layout": "PolymerElements/app-layout#2.0-preview",
    "app-route": "PolymerElements/app-route#2.0-preview",
    "iron-flex-layout": "PolymerElements/iron-flex-layout#2.0-preview",
    "iron-icon": "PolymerElements/iron-icon#2.0-preview",
    "iron-iconset-svg": "PolymerElements/iron-iconset-svg#2.0-preview",
    "iron-localstorage": "PolymerElements/iron-localstorage#2.0-preview",
    "iron-media-query": "PolymerElements/iron-media-query#2.0-preview",
    "iron-pages": "PolymerElements/iron-pages#2.0-preview",
    "iron-selector": "PolymerElements/iron-selector#2.0-preview",
    "paper-icon-button": "PolymerElements/paper-icon-button#2.0-preview",
    "webcomponentsjs": "webcomponents/webcomponentsjs#^1.0.0-rc.4",
    "paper-button": "PolymerElements/paper-button#2.0-preview",
    "paper-item": "PolymerElements/paper-item#2.0-preview",
    "paper-spinner": "PolymerElements/paper-spinner#2.0-preview",
    "iron-ajax": "PolymerElements/iron-ajax#2.0-preview",
    "paper-dialog": "PolymerElements/paper-dialog#2.0-preview",
    "iron-icons": "PolymerElements/iron-icons#2.0-preview",
    "paper-input": "PolymerElements/paper-input#2.0-preview"
  },
  "resolutions": {
    "polymer": "^2.0.0-rc.3"
  },
  "devDependencies": {
    "web-component-tester": "6.0.0-prerelease.5"
  },
  "private": true
}

```
and the piece of code :

```
      <paper-dialog id="updateData">
        <paper-input label="Serial Number"></paper-input>
        <div class="buttons">
          <paper-button dialog-dismiss>Cancel</paper-button>
          <paper-button autofocus on-tap="updateSync">Send</paper-button>
        </div>
      </paper-dialog>

```

The error in the document loading :

> Uncaught TypeError: Cannot read property 'addEventListener' of null
    at HTMLElement.attached (paper-input-container.html:513)

The error when click to paper-input :

Uncaught TypeError: Cannot read property '_inputElement' of undefined
    at HTMLElement.get _focusableElement [as _focusableElement] (paper-input.html:275)
    at HTMLElement._focusBlurHandler (paper-input-behavior.html:456)

It's strange if it works in your side

**Comment by MarcMouallem** [comment] 2017-04-22 05:08
Yea, not working for me either right after I had to reinstall my bower components. Had Polymer 2 working fine before that.

**Comment by MarcMouallem** [comment] 2017-04-22 05:28
Quick update, so it's a bug just reproduced it in the starter kit with a twist.

After initializing the starter kit with `polymer init` and adding a paper-input components to one of the views everything worked fine. HOWEVER, if you delete the bower_components folder and then regenerate it with `bower install` the problem will be reproduced.

I can't continue without this fixed, so I'll start looking into the source code, FML. SWAG, its from commit 615fa62c123eb7d644aa8c6b25ea67aba08f3cc6 from two days ago.

https://github.com/PolymerElements/paper-input/commit/615fa62c123eb7d644aa8c6b25ea67aba08f3cc6

**Comment by MarcMouallem** [comment] 2017-04-22 06:00
So much for my scientific wild ass guess :( The commit that breaks it for me is, drumroll please .... 7a5a24815717cdc05643ebc9d52d103000b45642.

Temporary workaround is just to use the previous commit, so modify your `bower.install` as so.
`    "paper-input": "PolymerElements/paper-input#19a2951041416d1d06a78a89e6ed547173030adc"
`

My work here is done, I'll let @notwaldorf take it from here.

**Comment by MarcMouallem** [comment] 2017-04-22 09:01
Okay, so I think I can explain everything.

16 days ago the [7639cf815e3d3cf2d953a0e412f1cc1e2d84f0df](https://github.com/Polymer/polymer/commit/7639cf815e3d3cf2d953a0e412f1cc1e2d84f0df) commit was made to the polymer repo adding back the `beforeRegister` lifecycle call back. In response @notwaldorf made the 7a5a24815717cdc05643ebc9d52d103000b45642 commit to the paper-input repo.

Now this is great, keeping the code clean, but it created a slight hitch. Now paper-input requires a version of polymer after the later [7639cf815e3d3cf2d953a0e412f1cc1e2d84f0df](https://github.com/Polymer/polymer/commit/7639cf815e3d3cf2d953a0e412f1cc1e2d84f0df) commit.

Bower in some cases is not resolving to the latest polymer version. For me I think this was because the polymerfire `bower.json` specifically listed `"polymer": "polymer/polymer#2.0.0-rc.3"` as a dependency and since my bower only required `"polymer": "polymer/polymer#^2.0.0-rc.3"`, `bower install` kept pulling version 2.0.0-rc.3.

FIX: Update your `bower.install` to require  `"polymer": "polymer/polymer#^2.0.0-rc.7"`. If bower ask which version to pull, be sure to select version 2.0.0-rc.7.

**Comment by mahdiridho** [comment] 2017-04-22 12:35
I have fixed my problem, just easy fix :

- remove all files on project folder
- remove also all hidden files on project folder
- new fresh install polymer 2.0, I was using polymer init (starter kit 2.0)
- install paper-input

it works well now, I don't know what is the real problem here

**Comment by MarcMouallem** [comment] 2017-04-22 13:10
^

**Comment by MarcMouallem** [comment] 2017-04-22 13:11
@mahdiridho ^

**Comment by MarcMouallem** [comment] 2017-04-22 13:17
@mahdiridho I tried to explain it as best as I could above. You really don't want to use those types of approaches to fix things, better to understand what's going on.

**Comment by pi4n0zik** [comment] 2017-04-23 21:53
I have the same problem since today after I run `bower update`

**Comment by notwaldorf** [comment] 2017-04-24 17:51
@MarcMouallem I think you're totally right, updated in 18b9cc8.

Going to close this, since the problem is definitely having the wrong version of Polymer installed. The solution is to delete your `bower_components` directory, and run `bower install` again.

**Closed by notwaldorf** 2017-04-24 17:51 UTC
Labels: pending-response

**Comment by tupaje1** [comment] 2017-04-24 18:00
Thanks everyone for your reply. I will make sure to have the correct bower versions installed.

**Comment by e111077** [comment] 2017-04-24 21:51
Updated `polymerfire` sorry about that!

**Comment by MarcMouallem** [comment] 2017-04-24 23:30
@notwaldorf and here I thought it wasn't possible to love Google more than I already do.
