### ISSUE TITLE
value-change event is fired twice for each keystroke

### ISSUE THREAD

**Issue by mercmobily** [PolymerElements/paper-input#421] opened 2016-08-09 05:40 UTC
### Description

A paper-input event will emit value-changed twice each time a key is pressed.
This makes it especially difficult when firing up validation AJAX calls for real-time validation.

This is similar to https://github.com/Polymer/paper-input/issues/33 (it was for Polymer 0.5); a Chrome bug was blamed: https://bugs.chromium.org/p/chromium/issues/detail?id=398527&thanks=398527&ts=1406661473 However, the but was fixed in Chrome in 2014 and yet the problem is still there.

### Expected outcome

The event is only fired once

### Actual outcome

The event is fired twice.

### Live Demo

https://jsbin.com/vojexe/edit?html,console,output

(BTW How come HTMLImports is not working in the JSbin?!?)

### Steps to reproduce

Just make up a paper-input element and listen to it:

    <dom-module id="my-element">
      <template>
        <paper-input id="pi"></paper-input>
      </template>
      <script>
        Polymer({
          is: 'my-element',
          attached: function() {
            this.listen(this.$.pi, 'value-changed', '_logChange');
          },

          _logChange: function(e) {
            console.log('fired');
          }
        });
      </script>
    </dom-module>

### Browsers Affected

Sorry, I could only check Chrome...

- [X] Chrome
- [?] Firefox
- [?] Safari 9
- [?] Safari 8
- [?] Safari 7
- [?] Edge
- [?] IE 11
- [?] IE 10

**Comment by notwaldorf** [comment] 2016-08-09 19:30
Closing as duplicate of https://github.com/PolymerElements/paper-input/issues/66. Please check that thread for more details

**Closed by notwaldorf** 2016-08-09 19:30 UTC

**Comment by mercmobily** [comment] 2016-08-10 00:55
Apologies.

**Comment by notwaldorf** [comment] 2016-08-10 00:57
No worries! :)

**Comment by mercmobily** [comment] 2016-08-10 00:59
I really make a point of really searching existing bugs... for this one, there were more than one and I had missed #66! I added a comment there, I hope it helps... will look harder next time!
