### ISSUE TITLE
dependency hell

### ISSUE THREAD

**Issue by gertcuykens** [PolymerElements/paper-input#687] opened 2019-01-26 12:56 UTC
https://jsbin.com/fafexes/edit?html,console,output

"error"
"Error: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
    at https://unpkg.com/@polymer/polymer@3.1.0/lib/elements/dom-module.js?module=:175:16"

I assume this repo is dead? But can't find the lit alternative?

**Comment by TimvdLippe** [comment] 2019-02-05 11:59
I don't get the duplication, but unpkg is definitely acting funky. Closing this as duplicate of https://github.com/unpkg/unpkg.com/issues/177

**Closed by TimvdLippe** 2019-02-05 11:59 UTC
