### ISSUE TITLE
paper-input fails to render correctly if invalid is bound to an undefined property

### ISSUE THREAD

**Issue by miztroh** [PolymerElements/paper-input#145] opened 2015-08-13 18:33 UTC
```
<paper-input label="ZIP or mailing code" always-float-label invalid="{{info.zip.invalid}}" error-message="{{info.zip.error}}" value="{{info.zip.value}}"></paper-input>
```

In the example above, if ``info.zip.invalid`` is undefined, the ``paper-input`` renders as follows:
![paper-input](https://cloud.githubusercontent.com/assets/2515209/9258174/8f357326-41bf-11e5-9e89-eb659cf4dc5a.jpg)
No error or warning is sent to the console.

``paper-input`` will render correctly if ``info.zip.invalid`` is initially defined.  If ``info.zip.invalid`` later becomes undefined, the ink effects stop working.

**Comment by notwaldorf** [comment] 2015-12-16 01:40
I can't reproduce this anymore. Here's a jsbin where it renders as invalid (since `invalid` is not falsy): http://jsbin.com/sexuvo/edit?html

![Uploading Screen Shot 2015-12-15 at 5.39.52 PM.png…]()

**Comment by miztroh** [comment] 2015-12-16 02:03
@notwaldorf Your test case wasn't reproducing the actual conditions.  Here's another that demonstrates what I was trying to describe.

http://jsbin.com/sogasusimo/edit?html,output

**Comment by notwaldorf** [comment] 2015-12-16 02:17
Ah, yes. Re-opening, but unfortunately that's a known Polymer core bug, not an element bug: https://github.com/Polymer/polymer/issues/2360

**Comment by notwaldorf** [comment] 2016-01-05 22:05
Going to close this, since this should be fixed when https://github.com/Polymer/polymer/issues/2360 is fixed, and there's nothing we can do in `paper-input` :(

**Closed by notwaldorf** 2016-01-05 22:05 UTC
