### ISSUE TITLE
paper-textarea autogrow generate bizzarre side effects when in a paper-dialog

### ISSUE THREAD

**Issue by kungufli** [PolymerElements/paper-input#125] opened 2015-07-21 10:45 UTC
When a paper-textarea is inside  paper-dialog, when the textarea try to autogrow as you write, the dialog will be resized horizontally.

**Comment by notwaldorf** [comment] 2015-07-27 12:05
I think historically the whole point of the `paper-textarea` was to autogrow to fit its content. If you really don't want that, you can wrap a plain `textarea` in a `paper-input-container`:
```
<paper-input-container always-float-label>
  <label>Hello</label>
  <textarea rows="3"></textarea>
</paper-input-container>
```

/cc @morethanreal in case I'm wrong about this :)

**Comment by notwaldorf** [comment] 2015-07-27 22:26
@kungufli Ah, I have an even better answer. `iron-autogrow-textarea` has a `maxRows` property, which will limit the max height of the textarea. There's a PR in flight to add this to `paper-textarea`, which should solve your proplem, I think: https://github.com/PolymerElements/paper-input/pull/124

**Comment by kungufli** [comment] 2015-07-28 09:29
@notwaldorf thank you for your feedback, `maxRows` is very welcomed, but didn't solve this problem. 
This is a short example of the bug:
![paper-textarea](https://cloud.githubusercontent.com/assets/12832388/8927945/68f93996-351b-11e5-9e67-b24bb9e18a8c.gif)
Also, in my opinion, the `paper-textarea` should resize vertically (adding rows as you write) inside a `paper-dialog` and not horizontally. 
For now I fixed the problem setting a fixed `width` for the `paper-dialog`.

**Comment by notwaldorf** [comment] 2015-08-03 17:07
@kungufli Can you repro this in a jsbin, or send me a snippet of how you're using this? Does the paper-textarea have a `width: 100%` and its parent keeps resizing or something?

**Comment by kungufli** [comment] 2015-08-04 08:50
@notwaldorf Adding `width: 100%` don't make any difference. I'm not sure how to add the latest Polymer dependencies in jsbin, but this is the code of the very simple example I posted earlier: 
```
<html>
  <head>
    <script src="../bower_components/webcomponentsjs/webcomponents-lite.min.js"></script>
    <link rel="import" href="../bower_components/paper-dialog/paper-dialog.html">
    <link rel="import" href="../bower_components/paper-input/paper-textarea.html">
  </head>
  <body class="fullbleed">
    <paper-dialog id="dialog">
      <div>paper-dialog</div>
      <paper-textarea label="paper-textarea"></paper-textarea>
    </paper-dialog>
  </body>

  <script>
    window.addEventListener('WebComponentsReady', function(e) {
      document.querySelector('#dialog').open();
    });
  </script>
</html>
```

**Comment by notwaldorf** [comment] 2015-08-04 19:23
Amazing repro steps, thanks! Taking a look now :)

**Comment by notwaldorf** [comment] 2015-08-04 19:29
@kungufli My easiest fix is to set a width on your dialog, and then the textarea will fill it and not grow. Does this work?
```
paper-dialog {
  width: 300px;
 }
```

**Comment by notwaldorf** [comment] 2015-08-04 19:34
The other alternative is to set a width on the textarea:
```
paper-textarea {
      display: block;
      width: 200px;
}
```

**Comment by notwaldorf** [comment] 2015-08-04 19:39
I think without either of those fixes, this is kind of working as designed: the `paper-textarea` doesn't have anything containing it, so it grows forever, and the `paper-dialog` tries to resize to accomodate its content, so it grows forever.

One of these two needs to bind its width :)

Let me know if this sounds reasonable and if I can close this.

**Comment by notwaldorf** [comment] 2015-08-10 18:37
Closing this, as I think this is within the "works as intended" reason (see explanation above).

**Closed by notwaldorf** 2015-08-10 18:37 UTC
Labels: pending-response

**Comment by bipin-nag** [comment] 2016-08-28 19:05
Kindly reopen this. The solution is not working, even if parent width is set it keeps on expanding.

**Comment by beckula** [comment] 2016-12-07 19:53
Version 1.7.0.
Just encountered this.  I have a paper-textarea inside a custom element that has a defined width. The text area starts to grow if I type a very long word with no spaces. It grows outside the bounds of the element and will keep going off the page if I keep typing.  It should auto wrap words that are too long.

```
<dom-module id="test-element">
<template>
  <style include="iron-flex iron-flex-alignment">
    :host {
      display: inline-block;
      width: 350px;
    }
  </style>

  <div class="layout horizontal end">
      <paper-textarea class="flex"
          max-length="[[maxLength]]"
          rows="1"
          max-rows="1"
          placeholder="Add Comment"
          value="{{text}}"></paper-textarea>

        <paper-icon-button
            icon="icons:check"
            on-tap="onSaveTap_"></paper-icon-button>

      <paper-icon-button
          icon="icons:clear"
          on-tap="onCancelTap_"></paper-icon-button>
    </div>
  </template>
</dom-module>
```
I also tried hard coding a fixed width to the parent div, but it had no effect.

`<div class="layout horizontal end" style="width:350px">`

It doesn't even work if I set an explicit width on paper-textarea:

`<paper-textarea style="width: 350px;"`

Here's a screenshot
![polymer issue](https://cloud.githubusercontent.com/assets/13319301/20983764/8dad98ec-bc72-11e6-86d9-8506fd07d96c.png)

**Comment by naxo8628** [comment] 2018-09-18 16:38
any solution of this?

**Comment by b3008** [comment] 2020-01-22 13:18
I encountered the same issue, the way I'm solving it for my use case is by nesting the `paper-textarea` element inside a `div`, and set the width of the parent of the actual `textarea`, to the width of the container `div`, also when detecting a resize event.

Hope this helps someone.


    resizePaperTextarea(inputItem) {
       
            inputItem.root.childNodes[2].children[1].textarea.style.overflow = "hidden";
            let width = window.getComputedStyle(inputItem.parent).width;
            
            inputItem.root.childNodes[2].style.width = width;
            inputItem.addEventListener("focus", (e)=>{
                let width = window.getComputedStyle(inputItem.parent).width;
                inputItem.root.childNodes[2].style.width = width;
            })

            window.addEventListener('resize', ()=>{
                inputItem.root.childNodes[2].style.width = ""
                setTimeout(()=>{
                    let width = window.getComputedStyle(inputItem.parent).width;
                inputItem.root.childNodes[2].style.width = width;
                },100);                
            })
             
    }

````
