### ISSUE TITLE
paper-input password on firefox android

### ISSUE THREAD

**Issue by srikkbhat** [PolymerElements/paper-input#305] opened 2016-01-06 20:04 UTC
1. Open the link http://embed.plnkr.co/DN2eKIIzIemHH31VPqo7/ on firefox on android.
2. Type a password.
3. Click backspace all the way to the front, removing all characters.
4. Now, start typing again. It is typing in reverse. Also it opens up text select menu on any further taps.

I use nexus 5x.

![paper-input-firefox-android](https://cloud.githubusercontent.com/assets/5298870/12153222/c6ea226e-b486-11e5-9095-32276026fe3f.png)

**Comment by notwaldorf** [comment] 2016-01-29 00:13
Seems like a duplicate of https://github.com/PolymerElements/paper-input/issues/273, which is "paper-input is super broken on mobile Firefox"

**Closed by notwaldorf** 2016-01-29 00:13 UTC
